import type { Product } from "@golfeexpress/types";

export const MOCK_MENU_CATEGORIES = ["Poke Bowls", "Boissons", "Desserts"];

export const MOCK_MENU_PRODUCTS: Product[] = [
  {
    id: "prod-poke-saumon",
    proId: "pro-poke-paradise",
    name: "Poke Saumon",
    description: "Saumon frais, avocat, edamame, riz vinaigré, sauce soja",
    price: 14.9,
    image: "🍣",
    category: "Poke Bowls",
    isAvailable: true,
    isFeatured: true,
  },
  {
    id: "prod-poke-thon",
    proId: "pro-poke-paradise",
    name: "Poke Thon",
    description: "Thon rouge, mangue, concombre, sésame, sauce épicée",
    price: 15.9,
    image: "🐟",
    category: "Poke Bowls",
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: "prod-poke-vege",
    proId: "pro-poke-paradise",
    name: "Poke Végétarien",
    description: "Tofu mariné, avocat, edamame, radis, sauce tahini",
    price: 12.9,
    image: "🥑",
    category: "Poke Bowls",
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: "prod-bubble-tea",
    proId: "pro-poke-paradise",
    name: "Bubble Tea",
    description: "Thé vert, perles de tapioca, lait",
    price: 5.5,
    image: "🧋",
    category: "Boissons",
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: "prod-limonade",
    proId: "pro-poke-paradise",
    name: "Limonade maison",
    description: "Citron frais, menthe, eau gazeuse",
    price: 4.5,
    image: "🍋",
    category: "Boissons",
    isAvailable: false,
    isFeatured: false,
  },
  {
    id: "prod-mochi",
    proId: "pro-poke-paradise",
    name: "Mochi glacé",
    description: "Boule de riz gluant fourrée glace vanille",
    price: 4.9,
    image: "🍡",
    category: "Desserts",
    isAvailable: true,
    isFeatured: false,
  },
];
